export const connectorTypeMap: Record<string, string> = {
    sdp: "sdp",
    firebase: "Firebase",
    mongo: "MongoDB",
    elasticsearch: "Elasticsearch",
    cockroachdb: "CockroachDB",
    saphana: "SAP HANA",
    sharepoint: "SharePoint",
    redis: "Redis",
    gitlab: "Gitlab",
    fileupload: "File Upload",
    cassandra: "Apache Cassandra",
    oracledb: "Oracle DB",
    dynamodb: "DynamoDB",
    mssql: "MS SQL",
    LOQ: "LOQ",
    "ceipal reports":"Ceipal Reports",
    hrone: "HROne",
    onehash: "OneHash",
    postgresql: "PostgreSQL",
    salesforce: "Salesforce",
    couchbase: "Couchbase",
    IBM: "IBM DB2",
    supabase: "Supabase",
    ceipal: "Ceipal",
    mysql: "MySQL",
    mariadb: "MariaDB",
    spotlight: "Spotlight",
    couchdb: "CouchDB",
    "business-central-dynamics": "Business Central Dynamics",
    sharepro: "SharePro"
  };
  