export const visualizationTypeMap: Record<string, string> = {
  verticalBar: "Vertical Bar",
  horizontalBar: "Horizontal Bar",
  stackedVerticalBar: "Stacked Vertical Bar",
  stackedHorizontalBar: "Stacked Horizontal Bar",
  stackedPercentageVerticalBar: "Stacked Percentage Vertical Bar",
  stackedPercentageHorizontalBar: "Stacked Percentage Horizontal Bar",
  line: "Line",
  area: "Area",
  stackedArea: "Stacked Area",
  pie: "Pie",
  doughnut: "Doughnut",
  polarArea: "Polar Area",
  radialBar: "Radial Bar",
  radar: "Radar",
  bubble: "Bubble",
  heatmap: "Heatmap",
  treemap: "Treemap",
  boxplot: "Boxplot",
  horizontalBoxplot: "Horizontal Boxplot",
  scatter: "Scatter",
  funnel: "Funnel",
  gauge: "Gauge",
  legacyMetric: "Legacy Metric",
  Table: "Table",
  "raw-table": "Raw Table"
};
